[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [ "environment" ]

[lib]
path = "snarkos/lib.rs"

[[bin]]
name = "snarkos"
path = "snarkos/main.rs"

#[[bin]]
#name = "main"
#path = "src/main.rs"

[dependencies]
backoff = { version = "0.4", features = ["tokio"] }
bytes = { version = "1" }
dotenv = { version = "0.15" }
futures = { version = "0.3" }
hyper = { version = "0.14" }
hyper-tls = { version = "0.5" }
indexmap = { version = "1.9", features = ["rayon"] }
once_cell = { version = "1.13.0" }
parking_lot = { version = "0.12" }
rusoto_core = { version = "0.48" }
tokio-util = { version = "0.7.3" }
warp = { version = "0.3" }

[dependencies.snarkos-environment]
path = "./environment"
version = "2.0.2"

[dependencies.snarkvm]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "7555dc0"
features = ["circuit", "console", "parallel", "utilities"]

[dependencies.aleo-std]
version = "0.1.14"
default-features = false

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"

[dependencies.clap]
version = "3.2"
features = [ "derive" ]

[dependencies.colored]
version = "2.0"

[dependencies.crossterm]
version = "0.25"
optional = true

[dependencies.num_cpus]
version = "1"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"

[dependencies.reqwest]
version = "0.11.11"

[dependencies.rocksdb]
version = "0.19"
default-features = false
features = [ "lz4" ]

[dependencies.self_update]
version = "0.30"
features = [
  "archive-zip",
  "compression-zip-bzip2",
  "compression-zip-deflate",
  "compression-flate2"
]

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1"
features = [ "full" ]

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
features = [ "env-filter", "parking_lot" ]

[dependencies.tui]
version = "0.18"
optional = true

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.tempfile]
version = "3.2"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "thin"
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
